services:
  wadnooh:
    build:
      context: ./SudanTravelApp.API
      dockerfile: Dockerfile
    container_name: wadnooh-app
    restart: unless-stopped
    ports:
      - "5162:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      PublicBaseUrl: https://wadnooh.com
      # FlightProvider__DuffelApiKey: duffel_live_xxx
      # AI__Provider: openai
      # AI__OpenAiApiKey: sk-xxx
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
