# fly.toml app configuration file generated for wadnooh
app = "wadnooh"
primary_region = "fra"

[build]
  dockerfile = "SudanTravelApp.API/Dockerfile"

[env]
  ASPNETCORE_ENVIRONMENT = "Production"
  ASPNETCORE_URLS = "http://0.0.0.0:8080"
  PublicBaseUrl = "https://wadnooh.com"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  timeout = "5s"
  grace_period = "20s"
  method = "GET"
  path = "/api/flights/status"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
